### ISSUE TITLE
Issues with "loose application" pattern as applied to Boost EE application

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/boost#127]
As noted [here](https://github.com/OpenLiberty/open-liberty/issues/4548) (sorry, that's a lot to read through, you don't really have to)... the default app monitoring in Liberty uses a 500 ms polling interval.   That seems to result in a "double update" in LMP scenarios.

Not sure why... could be worth investigating...and/or... maybe Boost should use a longer interval.

**Comment by scottkurz** [comment]
This is all assuming that `mvn compile` does indeed result in an app update... I'm assuming it will, but haven't tried it..and not 100% sure.   

Someone should try it first.

**Comment by chyt** [comment]
`mvn compile` should trigger the app update. We give this advice in Open Liberty guides. See https://github.com/OpenLiberty/guides-common/issues/121#issuecomment-388937813

**Comment by scottkurz** [comment]
So I tried this for the EE case, for the src/it/test-jaxrs-2.0 app in the branch: https://github.com/ajm01/boost/tree/boostMavenExt and found a couple issues:

1. we're using dropins, not the loose application, so `mvn compile` doesn't update the app.
2. `mvn package` can't package a started server.   Guessing the reason is what led us to add the alt. output location [here](https://github.com/WASdev/ci.maven/blob/841f164c01da6b07e6ba847f297dea604068a91c/liberty-maven-app-parent/pom.xml#L93-L95) in the LMP.

Once these are addressed, it's worth going back to the original issue:

3. What should the default app monitor polling be?  

I'm assuming there's nothing wrong with the LMP causing 500 ms to not work well... (though I admit I haven't looked into the issue).

**Comment by scottkurz** [comment]
Going to re-title this issue as "loose app issues with EE".

**Comment by scottkurz** [comment]
OK, not sure strictly speaking the issue 2. with 'package' is a loose issue... not opening another issue yet though.
