### ISSUE TITLE
Create a JDBC booster for EE7 and EE8, w/o auth, using Derby as unspecified dependency

### ISSUE THREAD

**Issue by cherylking** [OpenLiberty/boost#158]
Create booster for JDBC for both EE7 and EE8

**Comment by scottkurz** [comment]
This should configure in turn (each referencing the previous) a:
* `<library>`
* `<jdbcDriver>`
* The 'DefaultDataSource' `<dataSource>`

Let's assume the connection pooling defaults are good enough to start with.

In this story, we don't care what other dependencies the user has specified...we're going to pull down Derby and use it.

With Derby running locally we can run with `user=user password=pwd`  type config, with auth meaningless.   Let's do that for this story.
