### ISSUE TITLE
Create separate project for boosters

### ISSUE THREAD

**Issue by chyt** [OpenLiberty/boost#163]
Since the boosters will not follow the same release cycle or versioning as boost-maven, I think they should really be contained in their own project. I propose that there should be a new `boost-boosters` project (or just `boosters` if that is repetitive) which uses a multi-module build to build/release all the boosters. 

I think that the BOMs can stay in boost-maven multi-module project, since we agreed that the versioning for the BOMs should remain consistent with the Boost Maven Plugin.

**Comment by cherylking** [comment]
So you are saying there would be a folder called boost-boosters at the same level as boost-maven and boost-gradle? Would those boosters be shared by those?

**Comment by scottkurz** [comment]
Same essential issue as #187
