### ISSUE TITLE
If Spring Boot application property server.address is not set default should be to use * host

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/boost#168]
The default behavior for Spring Boot JARs (using Tomcat/Jetty/Undertow) when `server.address` is not set is to bind to all available hosts on the machine (e.g. use `host="*"` in Liberty).  Right now the BoostServer configured for a Spring Boot Liberty uber JAR will default to not setting the `host` value for the `<httpEndpoint />` which will cause Liberty to use `localhost` by default.  This should be changed to use `host="*"` by default.

**Comment by scottkurz** [comment]
I've been closing out some of our old issues.  @anjumfatima90 , @tjwatson .. is this still relevant with the work in #288, for example?

**Comment by anjumfatima90** [comment]
We can close this issue. It has been addressed in pull request #288.
