### ISSUE TITLE
Implicitly configure Liberty features based on Spring Boot configuration

### ISSUE THREAD

**Issue by awisniew90** [OpenLiberty/boost#17]
Any Liberty features that need to be defined in the server.xml should be implicitly determined based on the Spring Boot starter configuration.

**Comment by scottkurz** [comment]
In particular:
* If the Spring boot application uses JSPs then a jsp feature is needed
* if WebSocket is needed then a webSocket feature is needed
* If https is required then the transportSecurity-1.0 feature is needed

Not sure if we want to take on calculating the version as part of this issue (jsp-2.2 or 2.3... websocket-1.0 or 1.1) or save until later.

**Comment by awisniew90** [comment]
JSP configuration is dependent on war archive support for Spring Boot. (Typically, a Spring Boot project with JSPs would be packaged as a war). Moving that support over to issue #45

**Comment by awisniew90** [comment]
The SSL support has been delivered to the Maven plugin.  This also needs to be ported to the Gradle plugin before this item can be closed.
