### ISSUE TITLE
Allow for parameterization with DB credentials (userid/password)

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/boost#211]
We need to provide a convenient solution in a dev use case, but one which also works in the various cloud environments.  

(Yeah, that's pretty vague... but at this point we're serving the purpose of dividing up the TODOs for people to work on, so writing this issue is this is still of some value.)

**Comment by scottkurz** [comment]
Let's start by generating the server.xml to accept env variables.

**Comment by awisniew90** [comment]
This issue has been completed via other issues.
