### ISSUE TITLE
Configuration of the default host when useDefaultHost is set to true

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/boost#236]
While reviewing PR #220 I became concerned with the behavior we still have in the code when useDefaultHost is set to true.  In that case we still will try to grokk from the application.properties what the application wants and apply the settings to the defaultHost in the liberty server configuration.  This obviously still has a number of issues (for example #168).  In the long run we need to consider how the default host endpoint is configured when using the boost plugin in general.

For example, how should it be configurable for MicroProfile/Jakarta applications?  Should we try to have a consistent approach for configuration of the default host across Spring Boot and the standard MicroProfile/Jakarta applications?  If so then that likely will not require trying to deduce the configuration from the application.properties (or yaml etc.).  In the long run I think we need to try to avoid deducing the configuration of the default host settings from Spring Boot application properties because it is error prone.  If an application is choosing to useDefaultHost=true then it should be acceptable for them to have that default host be configured in some Boost specific way and ignore the server configuration settings from the Spring Boot application properties altogether.

**Comment by scottkurz** [comment]
I tend to agree and don't see how useDefaultHost=true is really feasible but we haven't settled on a decision to pull it out yet, and won't for a couple weeks at the earliest, anyway.

**Comment by scottkurz** [comment]
I think this too is superseded by #288 and more recent work.
