### ISSUE TITLE
Add a pom.xml to src/it to list all the integration tests as modules

### ISSUE THREAD

**Issue by cherylking** [OpenLiberty/boost#24]
We can also add some common properties and configuration as needed, instead of repeating it in each test pom.xml.

**Comment by cherylking** [comment]
Actually, since some of the tests need to list the spring-boot-starter-parent as their parent, we cannot use this new pom.xml for common config/properties. Adding this pom.xml does allow Eclipse to import all the tests as modules though and identify compilation errors.

**Comment by scottkurz** [comment]
Not sure if @cherylking had more planned for issue #24 than PR #27, so will leave this issue open after merging that.
