### ISSUE TITLE
Configure container-managed auth for all JDBC drivers

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/boost#271]
Noticed that Derby doesn't support the userid/password props like DB2, in terms of translating them into generation of the `<authData>` in the presence of JDBC booster.

Seems this should apply to any driver.    

I know my breakdown of the issues, when opened maybe implied otherwise, but didn't mean to leave Derby out.

**Comment by awisniew90** [comment]
Fixed by #274 274
