### ISSUE TITLE
Support URL datasource property

### ISSUE THREAD

**Issue by awisniew90** [OpenLiberty/boost#276]
The URL datasource property is implicitly supported by just prefixing the property with "boost.db." (i.e. boost.db.URL).  However, there are a few conflicts that may arise since we are defaulting several properties like databaseName, portNumber, and serverName.  These would not need to be configured if a URL is specified, and may in fact cause errors if the server is configured with all of these properties.  

This story requires some investigation into how Liberty handles the configuration of multiple properties like this.

**Comment by scottkurz** [comment]
I think to start we're just going to put the burden on the user not to configure property sets that would cause a collision (e.g. databaseName + url).   Close for now since basic url support present with #299.
