### ISSUE TITLE
Liberty defaultHttpEndpoint still active even when using SpringBoot port.

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/boost#39]
With the change in https://github.com/OpenLiberty/boost/pull/35 adding the **server.liberty.use-default-host** property set to _false_ we are defaulting to using the port from the SpringBoot app.

But the defaultHttpEndpoint is still configured to use port 9080.

Some history [here](https://github.com/OpenLiberty/open-liberty/issues/2591) references a decision but without going into detail.

Let's follow-up and understand the earlier discussion.

**Comment by awisniew90** [comment]
So the goal here is to have only the server port configured by the user to be open on the server, and there are currently two options we are exploring to accomplish this. We can either keep the "server.liberty.use-default-host=false" bootstrap property and disable the defaultHttpEndpoint, or we can have the boost plugin map the server.port of the application to our defaultHttpEndpoint. 

The problem with option 1 is that disabling the defaultHttpEndpoint will affect our Helm charts (and potentially other tooling). The problem with option 2 is that many of the methods to override the server port at runtime are no longer available to the user.  

The following stackoverflow post has a comment that sums up the various override options that a Spring Boot user has at runtime: https://stackoverflow.com/questions/21083170/spring-boot-how-to-configure-port (4th answer).  They are a mix of setting environment variables, jvm system properties, application arguments, and properties file overrides. 

By having Boost copy the server.port to bootstrap.properties, the only option here that works is setting "-Dserver.port=" at the command line.  By instead using "server.liberty.use-default-host=false”, all of these options work with the exception of the application arguments (i.e. --server.port=  or --spring.application.json= ). 

Ideally, we would want to have the boost uber jar function the same as the Spring Boot uber jar with most of these override options available. However, I’m not sure if that is possible by using our defaultHttpEndpoint without changes to Liberty code.

**Comment by cherylking** [comment]
As far as getting things from application.properties, that file is actually configurable using the system  property spring.config.location. So we should take that into account also.

**Comment by awisniew90** [comment]
True - but at runtime, I don't think we'd be able to process that file without changes to the Liberty Launcher.

**Comment by tjwatson** [comment]
How do we think helm charts for Liberty will work with the uber JAR?  It seems it would be a different animal.  Do we know what to test for to make sure the helm charts work as-is with the Liberty uber JAR?

**Comment by scottkurz** [comment]
I think this is superseded by more recent work such as #288
